### ISSUE TITLE
建议加大更新力度

### ISSUE THREAD

**Issue by yijunc** [mazeyang/mazeyang.github.io#1]

**Comment by yijunc** [comment]
https://github.com/mazeyang/mazeyang.github.io/blob/8548c193f886ad2b1ecb1da6e1d9d26a2559e0f1/_config.yml#L54 
你只要用户名就好了，自动加前面的链接的

**Comment by mazeyang** [comment]
> https://github.com/mazeyang/mazeyang.github.io/blob/8548c193f886ad2b1ecb1da6e1d9d26a2559e0f1/_config.yml#L54
> 
> 
> 你只要用户名就好了，自动加前面的链接的

好的收到，谢谢陈巨 :heart:
